# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mipantalla.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from base_datos import conn


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.nombre.setGeometry(QtCore.QRect(140, 50, 113, 23))
        self.nombre.setObjectName("nombre")
        self.label0 = QtWidgets.QLabel(self.centralwidget)
        self.label0.setGeometry(QtCore.QRect(70, 50, 54, 15))
        self.label0.setObjectName("label0")

        self.siglas = QtWidgets.QLineEdit(self.centralwidget)
        self.siglas.setGeometry(QtCore.QRect(140, 80, 113, 23))
        self.siglas.setObjectName("siglas")
        self.label01 = QtWidgets.QLabel(self.centralwidget)
        self.label01.setGeometry(QtCore.QRect(70, 80, 54, 15))
        self.label01.setObjectName("label01")

        self.estadio = QtWidgets.QLineEdit(self.centralwidget)
        self.estadio.setGeometry(QtCore.QRect(140, 110, 113, 23))
        self.estadio.setObjectName("estadio")
        self.label02 = QtWidgets.QLabel(self.centralwidget)
        self.label02.setGeometry(QtCore.QRect(70, 110, 54, 15))
        self.label02.setObjectName("label02")

        self.seguidores = QtWidgets.QLineEdit(self.centralwidget)
        self.seguidores.setGeometry(QtCore.QRect(140, 140, 113, 23))
        self.seguidores.setObjectName("seguidores")
        self.label03 = QtWidgets.QLabel(self.centralwidget)
        self.label03.setGeometry(QtCore.QRect(70, 140, 70, 15))
        self.label03.setObjectName("label03")

        self.campeonatos = QtWidgets.QLineEdit(self.centralwidget)
        self.campeonatos.setGeometry(QtCore.QRect(140, 170, 113, 23))
        self.campeonatos.setObjectName("campeonatos")
        self.label04 = QtWidgets.QLabel(self.centralwidget)
        self.label04.setGeometry(QtCore.QRect(70, 170, 70, 15))
        self.label04.setObjectName("label04")

        self.guardar = QtWidgets.QPushButton(self.centralwidget)
        self.guardar.setGeometry(QtCore.QRect(70, 210, 211, 21))
        self.guardar.setObjectName("guardar")
        self.actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.actualizar.setGeometry(QtCore.QRect(70, 250, 211, 21))
        self.actualizar.setObjectName("actualizar")

        self.listaEquipos = QtWidgets.QTableWidget(self.centralwidget)
        self.listaEquipos.setGeometry(QtCore.QRect(300, 50, 450, 400))
        self.listaEquipos.setObjectName("listaEquipos")
        self.listaEquipos.setColumnCount(5)
        self.listaEquipos.setHorizontalHeaderLabels(["Nombre", "Siglas", "Estadio", "Seguidores", "Campeonatos"])
        self.listaEquipos.setRowCount(0)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.crear_base()
        self.obtener_informacion()
        self.guardar.clicked.connect(self.guardar_informacion)
        self.actualizar.clicked.connect(self.obtener_informacion)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestión de Equipos"))
        self.label0.setText(_translate("MainWindow", "Nombre"))
        self.label01.setText(_translate("MainWindow", "Siglas"))
        self.label02.setText(_translate("MainWindow", "Estadio"))
        self.label03.setText(_translate("MainWindow", "Seguidores"))
        self.label04.setText(_translate("MainWindow", "Campeonatos"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))
        self.actualizar.setText(_translate("MainWindow", "Actualizar"))

    def crear_base(self):
        cursor = conn.cursor()
        cadena_sql = 'CREATE TABLE IF NOT EXISTS Equipo (nombre TEXT, siglas TEXT, estadio TEXT, seguidores INTEGER, campeonatos INTEGER)'
        cursor.execute(cadena_sql)
        cursor.close()

    def guardar_informacion(self):
        cursor = conn.cursor()
        nombre = self.nombre.text()
        siglas = self.siglas.text()
        estadio = self.estadio.text()
        seguidores = int(self.seguidores.text())
        campeonatos = int(self.campeonatos.text())
        cadena_sql = """INSERT INTO Equipo (nombre, siglas, estadio, seguidores, campeonatos) VALUES (?, ?, ?, ?, ?)"""
        cursor.execute(cadena_sql, (nombre, siglas, estadio, seguidores, campeonatos))
        conn.commit()
        cursor.close()
        self.obtener_informacion()

    def obtener_informacion(self):
        cursor = conn.cursor()
        cadena_consulta_sql = "SELECT * from Equipo"
        cursor.execute(cadena_consulta_sql)
        informacion = cursor.fetchall()
        self.listaEquipos.setRowCount(len(informacion))
        for i, fila in enumerate(informacion):
            for j, valor in enumerate(fila):
                self.listaEquipos.setItem(i, j, QtWidgets.QTableWidgetItem(str(valor)))
        cursor.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
